config/routes.rb
Rails.application.routes.draw do
  get 'public_meets/new'

  root 'public_posts#index'
  get 'categorias/:id', to: 'public_posts#posts_category', as: 'posts_category'
  get 'articulos/:url', to: 'public_posts#show', as: 'posts_show'

  resources :meets
  get 'citas', to: 'public_meets#new', as: 'citas'
  post 'create_meet', to: 'public_meets#create_meet', as: 'create_meet'

  devise_for :users
  resources :categories
   resources :ads
  resources :comments
  post 'create_comment', to: 'public_posts#create_comment', as: 'create_comment'
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'post#index'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SuperBlog" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>


    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->


    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body style="background-color: white">

    <div class="navbar navbar-default navbar-static-top barra-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><strong> Blog de Rails</strong>-<small>Administración</small></a>

        <div class="col-md-2">
          <ul class="nav navbar-nav">
          <li  class="current_page_item"><%= link_to "Menú Publico", root_path  %></li>

        </ul>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <p><i><small>Estas logueado como: <%= current_user.email %></small></i></p>
            <h3>Menú</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Articulos", posts_path  %></li>
              <li><%= link_to "Categorias", categories_path  %></li>
              <li><%= link_to "Comentarios", comments_path  %></li>
              <li><%= link_to "Anuncios", ads_path  %></li>
              <li><%= link_to "Citas", meets_path  %></li>
              <li><%= link_to "SALIR", destroy_user_session_path, method: :delete  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->
<hr>
      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "OppaBlog" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
  <div id="wrapper">
    <div id="header-wrapper">
      <div id="header">
        <div id="logo">
          <h1><a href="#">Oppas</a></h1>
          <p>Todo sobre Oppas en el blog más completo</p>
        </div>
      </div>
    </div>
    <!-- end #header -->
    <div id="menu">
      <ul>
        <li  class="current_page_item"><%= link_to "Articulos", root_path  %></li>
        <li><%= link_to "Citas", citas_path  %></li>
      </ul>
      <div class="col-md-2">
          <% if user_signed_in? %>
              <%= link_to "Panel", posts_path  %>Hola <%= current_user.email  %>
          <% else %>
              <li> <%= link_to "Acceder", new_user_session_path  %></li>
          <% end %>

      </div>
    </div>
    <!-- end #menu -->
    <div id="page">
      <div id="page-bgtop">
        <div id="page-bgbtm">
          <div id="content">
            <div class="row">
              <div class="col-lg-9">
                <%= bootstrap_flash %>
                <%= yield %>
              </div>
            </div><!--/row-->
          </div>
          <!-- end #content -->
          <div id="sidebar">
            <ul>

              <li>
                <h3>Categorias</h3>
                <ul class="nav nav-list">
                  <%  list_categories.each do |c|%>
                      <li><%= link_to c.name, posts_category_path(c.id)  %></li>
                  <% end %>
                </ul>
              </li>
              <li>
                <h3 class="nosotros">Nostros</h3>
                <ul class="nav nav-list">
                  <label>
                    Somos un blog dedicado
                    a ofrecer informacion
                    acerca de Oppas
                  </label>
                </ul></li>
              <li>
                <div class="anuncios">
                  <%= link_to ad_available.link, target:'_blank' do %>
                      <%= image_tag ad_available.image,  width: 230, height: 500 %>
                  <% end %>
                </div>
              </li>
              <li>
              </li>
            </ul>
          </div>
          <!-- end #sidebar -->
          <div style="clear: both;">&nbsp;</div>
        </div>
      </div>
    </div>
    <!-- end #page -->
  </div>
  <div id="footer">
    <p>&copy; Untitled. All rights reserved.</p>
  </div>
  <!-- end #footer -->

  </body>
</html>